Repository blarth/drivent-front, pull requests merged in 2022-06, with the labels that each got.

#3 Feat/payment
  src/assets/fonts/Roboto-Regular.ttf
  src/assets/styles/style.css
  src/components/Dashboard/Subtitle/index.js
  src/components/Dashboard/Subtitle/style.js
  src/components/Dashboard/Title/index.js
  src/components/Dashboard/Title/style.js
  src/components/Payment/CardInsertionForm/index.js
  src/components/Payment/TicketDescription/index.js
  src/components/Payment/TicketDescription/style.js
  src/components/TicketChoice/HotelOptions.js
  src/components/TicketChoice/ReserveTicket.js
  src/components/TicketChoice/TicketOptions.js
  src/components/TicketChoice/index.js
  src/contexts/TicketChoiceContext.js
  src/pages/Dashboard/Payment/index.js
Labels: bug, enhancement

#7 Feat/payment
  src/App.js
  src/assets/images/confirmationIcon.png
  src/components/Payment/CardInsertionForm/index.js
  src/components/Payment/PaymentConfirmation/index.js
  src/components/Payment/PaymentConfirmation/style.js
  src/components/Payment/TicketDescription/index.js
  src/components/TicketChoice/TicketOptions.js
  src/contexts/PurchasedTicketContext.js
  src/pages/Dashboard/Hotel/index.js
  src/pages/Dashboard/Payment/index.js
Labels: bug, feature

#8 feat: hotels description
  src/components/Hotel/HotelDescription/index.js
  src/components/Hotel/HotelDescription/style.js
  src/components/Hotel/HotelInformation/index.js
  src/components/Hotel/HotelInformation/style.js
  src/contexts/PurchasedTicketContext.js
  src/hooks/api/useHotels.js
  src/pages/Dashboard/Hotel/index.js
  src/pages/Dashboard/Hotel/style.js
  src/services/hotelApi.js
Labels: feature
